import * as stylex from "@stylexjs/stylex";

export const colors = stylex.defineVars({
  ink: "#171712",
  muted: "#6f6b60",
  paper: "#fffdf7",
  line: "#d8d2c4",
  accent: "#315f45",
  accentInk: "#f6fff8",
  soft: "#e8e2d3",
  page: "#f5f2e8",
});

export const styles = stylex.create({
  page: {
    minHeight: "100vh",
    color: colors.ink,
    background: "radial-gradient(circle at top left, #fffdf7 0, #f5f2e8 45%, #ede8da 100%)",
    fontFamily: "Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
  },
  shell: { width: "min(1180px, calc(100% - 32px))", marginInline: "auto" },
  header: {
    minHeight: 78,
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 24,
    borderBottomWidth: 1,
    borderBottomStyle: "solid",
    borderBottomColor: colors.line,
    "@media (max-width: 620px)": {
      alignItems: "flex-start",
      flexDirection: "column",
      paddingBlock: 18,
    },
  },
  nav: { display: "flex", gap: 22, flexWrap: "wrap", "@media (max-width: 620px)": { gap: 14 } },
  navLink: { textDecoration: "none", color: { default: colors.muted, ":hover": colors.ink } },
  brand: { display: "inline-flex", alignItems: "center", gap: 10, fontWeight: 800, textDecoration: "none", letterSpacing: "-0.02em" },
  brandMark: { display: "grid", placeItems: "center", width: 34, height: 34, borderRadius: "50%", backgroundColor: colors.ink, color: "#fff", fontFamily: "ui-monospace, SFMono-Regular, Menlo, monospace", fontSize: 13 },
  footer: { display: "flex", justifyContent: "space-between", gap: 20, paddingBlockStart: 32, paddingBlockEnd: 50, borderTopWidth: 1, borderTopStyle: "solid", borderTopColor: colors.line, color: colors.muted, fontSize: 14, "@media (max-width: 620px)": { alignItems: "flex-start", flexDirection: "column" } },
  hero: { minHeight: 560, display: "grid", gridTemplateColumns: "minmax(0, 1.4fr) minmax(280px, 0.6fr)", gap: 60, alignItems: "center", paddingBlock: 84, "@media (max-width: 860px)": { gridTemplateColumns: "1fr", gap: 28, minHeight: "auto", paddingBlock: 64 } },
  heading1: { maxWidth: 820, marginBottom: 18, fontSize: "clamp(3rem, 8vw, 6.8rem)", lineHeight: 0.92, letterSpacing: "-0.065em" },
  heading1Narrow: { fontSize: "clamp(2.8rem, 7vw, 5.8rem)" },
  heading2: { letterSpacing: "-0.035em" },
  lede: { maxWidth: 720, color: "#4d4a42", fontSize: "clamp(1.1rem, 2vw, 1.35rem)", lineHeight: 1.6 },
  eyebrow: { marginBottom: 10, color: colors.accent, fontSize: 12, fontWeight: 800, letterSpacing: "0.13em", textTransform: "uppercase" },
  surface: { borderWidth: 1, borderStyle: "solid", borderColor: colors.line, borderRadius: 18, backgroundColor: colors.paper, boxShadow: "0 16px 50px rgba(70, 61, 43, 0.06)" },
  flowCard: { display: "flex", flexDirection: "column", gap: 14, padding: 28 },
  flowCode: { paddingBlock: 12, paddingInline: 14, borderRadius: 10, backgroundColor: colors.soft, overflowWrap: "anywhere" },
  flowStep: { paddingInlineStart: 12, color: colors.muted, fontSize: 14 },
  searchBox: { maxWidth: 720, display: "flex", gap: 10, marginBlockStart: 30, "@media (max-width: 620px)": { flexDirection: "column" } },
  searchInput: { width: "100%", minWidth: 0, paddingBlock: 16, paddingInline: 18, borderWidth: 1, borderStyle: "solid", borderColor: colors.line, borderRadius: 12, backgroundColor: colors.paper, color: colors.ink },
  button: { display: "inline-flex", alignItems: "center", justifyContent: "center", paddingBlock: 14, paddingInline: 18, borderWidth: 1, borderStyle: "solid", borderColor: colors.accent, borderRadius: 12, backgroundColor: { default: colors.accent, ":hover": "#284f39" }, color: colors.accentInk, fontWeight: 750, textDecoration: "none", cursor: "pointer" },
  buttonSecondary: { backgroundColor: { default: "transparent", ":hover": colors.soft }, color: colors.accent },
  section: { paddingBlock: 64 },
  narrowTop: { paddingBlockStart: 72, minHeight: "62vh" },
  sectionHeading: { display: "flex", alignItems: "flex-end", justifyContent: "space-between", gap: 24, marginBottom: 24, "@media (max-width: 620px)": { alignItems: "flex-start", flexDirection: "column" } },
  cardGrid: { display: "grid", gridTemplateColumns: "repeat(3, minmax(0, 1fr))", gap: 18, "@media (max-width: 860px)": { gridTemplateColumns: "1fr 1fr" }, "@media (max-width: 620px)": { gridTemplateColumns: "1fr" } },
  card: { padding: 24 },
  cardTitle: { marginBottom: 12, fontSize: 23 },
  bodyCopy: { lineHeight: 1.55 },
  tagRow: { display: "flex", flexWrap: "wrap", gap: 7, marginBlock: 14 },
  tag: { paddingBlock: 6, paddingInline: 9, borderRadius: 999, backgroundColor: colors.soft, fontSize: 12 },
  muted: { color: colors.muted },
  empty: { padding: 34 },
  detailGrid: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 18, marginBlockStart: 34, marginBlockEnd: 18, "@media (max-width: 860px)": { gridTemplateColumns: "1fr" } },
  panel: { padding: 26, marginBlock: 18 },
  facts: { display: "grid", gap: 12, margin: 0 },
  factRow: { display: "grid", gridTemplateColumns: "120px 1fr", gap: 12, paddingBottom: 10, borderBottomWidth: 1, borderBottomStyle: "solid", borderBottomColor: colors.line, "@media (max-width: 620px)": { gridTemplateColumns: "1fr", gap: 4 } },
  factTerm: { color: colors.muted },
  factValue: { margin: 0, overflowWrap: "anywhere" },
  buttonRow: { display: "flex", gap: 10, flexWrap: "wrap", marginBlockStart: 22 },
  monoWrap: { fontFamily: "ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace", overflowWrap: "anywhere" },
  pre: { overflowX: "auto", padding: 18, borderRadius: 12, backgroundColor: "#1e201c", color: "#f6f3e9", lineHeight: 1.6, fontFamily: "ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace" },
  previewList: { display: "grid", gap: 12 },
  previewNote: { padding: 18, borderWidth: 1, borderStyle: "solid", borderColor: colors.line, borderRadius: 12, backgroundColor: colors.paper, overflowWrap: "anywhere" },
  prose: { maxWidth: 820 },
  proseCopy: { lineHeight: 1.75 },
  srOnly: { position: "absolute", width: 1, height: 1, padding: 0, margin: -1, overflow: "hidden", clip: "rect(0, 0, 0, 0)", whiteSpace: "nowrap", borderWidth: 0 },
});
