import * as stylex from "@stylexjs/stylex";

export const colors = stylex.defineVars({
  ink: "#f7f4ff",
  muted: "#9299bc",
  paper: "#0a1020",
  line: "rgba(151, 73, 255, 0.34)",
  accent: "#ff3bbb",
  accentInk: "#090510",
  soft: "#151a30",
  page: "#050711",
});

export const styles = stylex.create({
  page: {
    minHeight: "100vh",
    color: colors.ink,
    background: "radial-gradient(circle at 82% -10%, rgba(126, 54, 255, 0.22), transparent 28%), radial-gradient(circle at 8% 16%, rgba(255, 47, 177, 0.12), transparent 24%), linear-gradient(180deg, #070a17 0%, #04060e 100%)",
    fontFamily: "Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
  },
  shell: {
    width: "min(1760px, calc(100% - 28px))",
    marginInline: "auto",
    "@media (max-width: 620px)": { width: "min(100% - 18px, 1760px)" },
  },
  header: {
    minHeight: 82,
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 22,
    paddingInline: 8,
    borderBottomWidth: 1,
    borderBottomStyle: "solid",
    borderBottomColor: "rgba(180, 75, 255, 0.25)",
    "@media (max-width: 900px)": { alignItems: "flex-start", flexDirection: "column", paddingBlock: 16 },
  },
  nav: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    flexWrap: "wrap",
    "@media (max-width: 620px)": { gap: 4 },
  },
  navLink: {
    paddingBlock: 10,
    paddingInline: 13,
    borderRadius: 10,
    textDecoration: "none",
    color: { default: colors.muted, ":hover": colors.ink },
    backgroundColor: { default: "transparent", ":hover": "rgba(255, 59, 187, 0.08)" },
  },
  brand: {
    display: "inline-flex",
    alignItems: "center",
    gap: 12,
    color: colors.ink,
    fontWeight: 900,
    fontStyle: "italic",
    fontSize: 22,
    textDecoration: "none",
    letterSpacing: "-0.04em",
  },
  brandMark: {
    display: "grid",
    placeItems: "center",
    width: 42,
    height: 42,
    borderRadius: "50%",
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: "rgba(255, 59, 187, 0.75)",
    background: "linear-gradient(145deg, #15152b, #090b17)",
    color: "#ff58c8",
    boxShadow: "0 0 24px rgba(255, 59, 187, 0.18)",
    fontFamily: "ui-monospace, SFMono-Regular, Menlo, monospace",
    fontSize: 13,
    fontStyle: "normal",
  },
  accountLink: {
    display: "inline-flex",
    alignItems: "center",
    gap: 10,
    paddingBlock: 7,
    paddingInline: 10,
    borderRadius: 14,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: "rgba(151, 73, 255, 0.30)",
    color: colors.ink,
    textDecoration: "none",
    backgroundColor: "rgba(11, 16, 35, 0.72)",
  },
  accountAvatar: {
    display: "grid",
    placeItems: "center",
    width: 34,
    height: 34,
    borderRadius: "50%",
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: "#ff3bbb",
    color: "#ff6acc",
    fontSize: 11,
    fontWeight: 900,
    boxShadow: "0 0 14px rgba(255, 59, 187, 0.18)",
  },
  accountName: { fontSize: 13, fontWeight: 800, whiteSpace: "nowrap" },
  footer: {
    display: "flex",
    justifyContent: "space-between",
    gap: 20,
    paddingBlockStart: 24,
    paddingBlockEnd: 34,
    borderTopWidth: 1,
    borderTopStyle: "solid",
    borderTopColor: "rgba(151, 73, 255, 0.18)",
    color: colors.muted,
    fontSize: 13,
    "@media (max-width: 620px)": { alignItems: "flex-start", flexDirection: "column" },
  },
  hero: {
    minHeight: 560,
    display: "grid",
    gridTemplateColumns: "minmax(0, 1.4fr) minmax(280px, 0.6fr)",
    gap: 60,
    alignItems: "center",
    paddingBlock: 84,
    "@media (max-width: 860px)": { gridTemplateColumns: "1fr", gap: 28, minHeight: "auto", paddingBlock: 64 },
  },
  heading1: { maxWidth: 820, marginBottom: 18, fontSize: "clamp(3rem, 8vw, 6.8rem)", lineHeight: 0.92, letterSpacing: "-0.065em" },
  heading1Narrow: { fontSize: "clamp(2.8rem, 7vw, 5.8rem)" },
  heading2: { letterSpacing: "-0.035em" },
  lede: { maxWidth: 720, color: colors.muted, fontSize: "clamp(1.1rem, 2vw, 1.35rem)", lineHeight: 1.6 },
  eyebrow: { marginBottom: 10, color: "#ff5ac7", fontSize: 12, fontWeight: 900, letterSpacing: "0.17em", textTransform: "uppercase" },
  surface: {
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: colors.line,
    borderRadius: 18,
    background: "linear-gradient(180deg, rgba(12, 18, 38, 0.98), rgba(7, 11, 24, 0.98))",
    boxShadow: "0 18px 60px rgba(0, 0, 0, 0.30), inset 0 0 0 1px rgba(255,255,255,0.015)",
  },
  flowCard: { display: "flex", flexDirection: "column", gap: 14, padding: 28 },
  flowCode: { paddingBlock: 12, paddingInline: 14, borderRadius: 10, backgroundColor: colors.soft, overflowWrap: "anywhere" },
  flowStep: { paddingInlineStart: 12, color: colors.muted, fontSize: 14 },
  searchBox: { maxWidth: 720, display: "flex", gap: 10, marginBlockStart: 30, "@media (max-width: 620px)": { flexDirection: "column" } },
  searchInput: { width: "100%", minWidth: 0, paddingBlock: 16, paddingInline: 18, borderWidth: 1, borderStyle: "solid", borderColor: colors.line, borderRadius: 12, backgroundColor: colors.paper, color: colors.ink },
  button: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    paddingBlock: 14,
    paddingInline: 18,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: "#ff4bc2",
    borderRadius: 12,
    background: { default: "linear-gradient(100deg, #ff3bbb, #b04cff)", ":hover": "linear-gradient(100deg, #ff61ca, #bf68ff)" },
    color: "#090510",
    boxShadow: "0 0 24px rgba(255, 59, 187, 0.20)",
    fontWeight: 850,
    textDecoration: "none",
    cursor: "pointer",
  },
  buttonSecondary: {
    background: { default: "rgba(11, 16, 35, 0.62)", ":hover": "rgba(255, 59, 187, 0.08)" },
    color: "#f0eaff",
    borderColor: "rgba(255, 89, 203, 0.48)",
    boxShadow: "none",
  },
  section: { paddingBlock: 64 },
  narrowTop: { paddingBlockStart: 72, minHeight: "62vh" },
  sectionHeading: { display: "flex", alignItems: "flex-end", justifyContent: "space-between", gap: 24, marginBottom: 24, "@media (max-width: 620px)": { alignItems: "flex-start", flexDirection: "column" } },
  cardGrid: { display: "grid", gridTemplateColumns: "repeat(3, minmax(0, 1fr))", gap: 18, "@media (max-width: 860px)": { gridTemplateColumns: "1fr 1fr" }, "@media (max-width: 620px)": { gridTemplateColumns: "1fr" } },
  card: { padding: 24 },
  cardTitle: { marginBottom: 12, fontSize: 23 },
  bodyCopy: { lineHeight: 1.55 },
  tagRow: { display: "flex", flexWrap: "wrap", gap: 7, marginBlock: 14 },
  tag: { paddingBlock: 6, paddingInline: 9, borderRadius: 999, backgroundColor: colors.soft, fontSize: 12 },
  muted: { color: colors.muted },
  empty: { padding: 34 },
  detailGrid: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 18, marginBlockStart: 34, marginBlockEnd: 18, "@media (max-width: 860px)": { gridTemplateColumns: "1fr" } },
  panel: { padding: 26, marginBlock: 18 },
  facts: { display: "grid", gap: 12, margin: 0 },
  factRow: { display: "grid", gridTemplateColumns: "120px 1fr", gap: 12, paddingBottom: 10, borderBottomWidth: 1, borderBottomStyle: "solid", borderBottomColor: colors.line, "@media (max-width: 620px)": { gridTemplateColumns: "1fr", gap: 4 } },
  factTerm: { color: colors.muted },
  factValue: { margin: 0, overflowWrap: "anywhere" },
  buttonRow: { display: "flex", gap: 10, flexWrap: "wrap", marginBlockStart: 22 },
  monoWrap: { fontFamily: "ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace", overflowWrap: "anywhere" },
  pre: { overflowX: "auto", padding: 18, borderRadius: 12, backgroundColor: "#080c18", color: "#f6f3ff", borderWidth: 1, borderStyle: "solid", borderColor: colors.line, lineHeight: 1.6, fontFamily: "ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace" },
  previewList: { display: "grid", gap: 12 },
  previewNote: { padding: 18, borderWidth: 1, borderStyle: "solid", borderColor: colors.line, borderRadius: 12, backgroundColor: colors.paper, overflowWrap: "anywhere" },
  prose: { maxWidth: 820 },
  proseCopy: { lineHeight: 1.75 },
  srOnly: { position: "absolute", width: 1, height: 1, padding: 0, margin: -1, overflow: "hidden", clip: "rect(0, 0, 0, 0)", whiteSpace: "nowrap", borderWidth: 0 },
});
